version: '3.1'

services:
  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.front-end.nginx
      args:
        - CLIENT_ID=${CLIENT_ID}
        - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on:
      - server
    ports:
      - 80:80
      - 81:81
    restart: unless-stopped
    networks:
      - server
  server:
    build:
      args:
        - CLIENT_ID=${CLIENT_ID}
        - CLIENT_SECRET=${CLIENT_SECRET}
        - REDIRECT_URI=${REDIRECT_URI}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - WORKSPACE_USER=${WORKSPACE_USER}
        - REFRESH_TOKEN=${REFRESH_TOKEN}
        - WORKSPACE_INFO=${WORKSPACE_INFO}
    command: npm start -w @dot/server
